name: msds684-week6
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy>=1.26
  - scipy>=1.12
  - matplotlib>=3.8
  - seaborn>=0.13
  - jupyter
  - nbconvert
  - tqdm
  - pip:
    - torch>=2.2.0
    - torchvision>=0.17.0
    - gymnasium==1.0.0
    - box2d-py>=2.3.5
